online features added
print('online feature1')
print('online feature2')
print('online feature3')
print('local feature4')
print('local feature5')
print('local feature5')
print('online feature3')
print('online feature3')
print('online feature3')
